spring:
  mvc:
    problemdetails:
      enabled: true

# Actuator properties
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: '*'
  endpoint:
    beans:
      enabled: true
    health:
      enabled: true
      show-details: always

# Springdoc properties
springdoc:
  show-actuator: false